name: Build/test and validate PR

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "LICENCE"
      - "CODEOWNERS"
      - ".gitignore"
      - ".github/workflows/deploy.yaml"
      - ".github/workflows/manual-deploy-dev.yaml"
      - ".github/workflows/playwright.yaml"
      - ".github/workflows/security.yaml"
      - ".github/dependabot.yaml"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-pr:
    name: Build and test
    uses: navikt/mob-gha-workflows/.github/workflows/node-build-pr.yaml@fix_404
    secrets: inherit
