name: Playwright Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    uses: navikt/moby-gha-workflows/.github/workflows/playwright.yaml@chore/fjerne-navikt-scope
    secrets: inherit