name: Playwright Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  playwright-test:
    name: Playwright test
    uses: navikt/monster-gha-workflows/.github/workflows/playwright.yaml@main
